name: test

on: push

jobs:
  test:
    name: checkout
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
